# Generated by Django 4.1.4 on 2023-02-28 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.IntegerField(blank=True, null=True)),
                ("full_name", models.CharField(blank=True, max_length=50, null=True)),
                ("image", models.ImageField(blank=True, upload_to="media")),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("university", models.CharField(blank=True, max_length=50, null=True)),
                ("major", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
