# Generated by Django 4.1.4 on 2023-03-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0006_task_has_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filesubmission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="education.student",
            ),
        ),
    ]
