# Generated by Django 4.1.4 on 2023-02-20 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SingletonModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instituation",
            fields=[
                (
                    "singletonmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="landingPage.singletonmodel",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("home_title", models.CharField(max_length=100)),
                ("home_description", models.CharField(max_length=300)),
                ("mission", models.CharField(max_length=300)),
                ("vission", models.CharField(max_length=300)),
            ],
            bases=("landingPage.singletonmodel",),
        ),
    ]
