# Generated by Django 4.1.4 on 2023-02-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingPage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instituation",
            name="vission",
            field=models.CharField(max_length=500),
        ),
    ]
