# Generated by Django 4.1.4 on 2023-02-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingPage", "0002_alter_instituation_vission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("image", models.ImageField(blank=True, upload_to="media")),
            ],
        ),
        migrations.RenameField(
            model_name="instituation", old_name="vission", new_name="about_us",
        ),
    ]
