# Generated by Django 4.1.4 on 2023-02-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingPage", "0003_programms_rename_vission_instituation_about_us"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("message_content", models.CharField(max_length=500)),
            ],
        ),
    ]
